### ISSUE TITLE
Nice Shader...

### ISSUE THREAD

**Issue by kazmi789** [Zenteon/ZN_FX#2]
hi sir ..... i just made this issue for appreciation and your hard-work for these awesome shaders .... performance hit very minimal and results are great ....  here are some result by using your shaders in addition to some other color correction shaders.        https://imgsli.com/MjUyMzU0        https://imgsli.com/MjUyMzU1              https://imgsli.com/MjUyMzU2

**Comment by Zenteon** [comment]
Thank you! Glad to see the community liking these

**Comment by GottaSlay** [comment]
Also wanted to say I really enjoy the shader and how light on performance it is! Looking forward to its development.
