### ISSUE TITLE
Kindly share discord info

### ISSUE THREAD

**Issue by kazmi789** [Zenteon/ZN_FX#3]
sir i do not know your discord ... if have any kindly share info ... thanks.

**Comment by Zenteon** [comment]
What kind of info would you like? The discord sever hasn't been officially announced so its mostly silent, but I can answer any questions relating to the shaders there

**Comment by darthmalak1986** [comment]
You can find Zen over reshade discord and I can help you too he explained to me , seems pretty cool guy

**Comment by kazmi789** [comment]
ok thanks .... i just want discord for updates ..... i am already member on reshade discord so for any help i will contact both you guys .

**Comment by darthmalak1986** [comment]
Contact him I'm not the dev and not that much experienced like him and I don't belong to he's support team

**Comment by Zenteon** [comment]
Discord link is in the readme, however it's still fairly empty as I'm waiting to announce it with the latest update. There is currently no support team, this pack is still in its infancy, but I'll can answer questions on either server in the meantime
