### ISSUE TITLE
the wireframes can show up upside down sometimes

### ISSUE THREAD

**Issue by Glitch31415** [Zenteon/ZN_FX#5]
![Screenshot_2024-06-17_23-33-13](https://github.com/Zenteon/ZN_FX/assets/123266631/71d9422b-8c53-469e-bef8-ea0ca174e315)
![Screenshot_2024-06-17_23-33-01](https://github.com/Zenteon/ZN_FX/assets/123266631/15961467-b1eb-441f-a272-a64a3059a991)
i don't know why this happens, but there's no option for rotation or flipping so it's unusable

**Comment by Zenteon** [comment]
Set up your depth buffer correctly with reshade
