### ISSUE TITLE
Zentient Wireframe seems not working with VR headset.

### ISSUE THREAD

**Issue by Shiroishi-Rosetta** [Zenteon/ZN_FX#6]
Hi sir, I am reaching out to report an issue I have encountered with the shaders while using it in an OpenXR environment. When running the shader in an OpenXR environment, the wireframe effects are not visible, and the shader appears to have no effect on the rendered image.

**Comment by Zenteon** [comment]
Make sure your depth buffer is set up correctly, and that the game has access to it: https://www.martysmods.com/depth-buffer-introduction/

**Comment by Shiroishi-Rosetta** [comment]
Thank you very much for your response.
﻿
I wanted to update you on the issue I was facing. It turns out that when using DirectX to launch the game, the depth buffer is correctly read and utilized without any issues. However, when attempting to use OpenXR, the depth buffer does not seem to be properly recognized or handled.
﻿
I appreciate your assistance.
